CC			= gcc
CFLAGS	=
TARGET	= client.o
OBJFILES= main.c
LDFLAGS	=

default: client

client: $(OBJFILES)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJFILES) $(LDFLAGS)

to: $(OBJFILES)
	$(CC) $(CFLAGS) -o $(path)/$(TARGET) $(OBJFILES) $(LDFLAGS)	